class common : public GlobalScript
{
public:
	static GlobalScript* Create()
	{
		static GlobalScript* inst = new GlobalScript("common", "Node", true, false);

		inst->AddStructElement(BaseType::GetTypeByName("identity_quaternion:quaternion")->m_GlobalId, "1.000000 0.000000 0.000000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("default_Gravity:vector")->m_GlobalId, "0.000000 -10.000000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("default_timestep:number")->m_GlobalId, "0.040000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("radian_to_degrees:number")->m_GlobalId, "57.295780", 0);
		inst->AddStructElement(BaseType::GetTypeByName("null_string:string")->m_GlobalId, 0, 0);
		inst->AddStructElement(BaseType::GetTypeByName("dont_fix_orient:truth")->m_GlobalId, "false", 0);
		inst->AddStructElement(BaseType::GetTypeByName("torso_vertical_orient:quaternion")->m_GlobalId, "0.707107 0.707107 0.000000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("legs_vertical_orient:quaternion")->m_GlobalId, "0.707107 -0.707107 0.000000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("subdir:Entity")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("foundancester:truth")->m_GlobalId, "", 0);
		inst->AddStructElement(706, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PLAYER_NODE:Entity")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("GENERAL_CUTSCENEPLAYING:truth")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("LAST_DYNAMIC_SOUNDENTITY:Entity")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("GENERAL_NONSHOOTING_ENEMY:truth")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("DEFAULT_VEHICLE_OFFSET:number")->m_GlobalId, "-1.388272", 0);
		inst->AddStructElement(BaseType::GetTypeByName("EMPTY_STRING:string")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("DB_ANIMDICT:Entity")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_DISABLE:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_DYNAMIC:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_INVISIBLE:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_COLL_DISABLE:integer")->m_GlobalId, "64", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_FRAGMENT_UNLOADED:integer")->m_GlobalId, "256", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NODE_PURGENAMES:integer")->m_GlobalId, "512", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_NONE:integer")->m_GlobalId, "0", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_SOLID:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_BULLETPROOF:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_OPAQUE:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_CAMERABLOCK:integer")->m_GlobalId, "8", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_TRIGGER:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_NAVIGATIONBLOCK:integer")->m_GlobalId, "32", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_PHYSICSONLY:integer")->m_GlobalId, "64", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_ACTIVATE_TRIGGER:integer")->m_GlobalId, "128", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COLL_ALL:integer")->m_GlobalId, "1024", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT1:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT2:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT3:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT4:integer")->m_GlobalId, "8", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT5:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT6:integer")->m_GlobalId, "32", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT7:integer")->m_GlobalId, "64", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT8:integer")->m_GlobalId, "128", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT9:integer")->m_GlobalId, "256", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT10:integer")->m_GlobalId, "512", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT11:integer")->m_GlobalId, "1024", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT12:integer")->m_GlobalId, "2048", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BIT13:integer")->m_GlobalId, "4096", 0);
		inst->AddStructElement(BaseType::GetTypeByName("GOD_MODE_LIMIT:number")->m_GlobalId, "2000.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAX_TIME_ZONES:integer")->m_GlobalId, "29", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_NORMAL:integer")->m_GlobalId, "0", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_FREEFALL:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_ABSOLUTE:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_SLIDE:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_TAKEOFF:integer")->m_GlobalId, "8", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PIVOT_DEFAULT:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BASE_TYPES_MAX_NUM:integer")->m_GlobalId, "24", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CHARACTER_TYPES_MAX_NUM:integer")->m_GlobalId, "23", 0);
		inst->AddStructElement(BaseType::GetTypeByName("ANIMAL_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TARGET_DUMMY_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "1", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CAMERA_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("OBJECT_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "100", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PLACEHOLDER_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PLACEHOLDER_PRIORITIES_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RESOURCE_TYPES_MAX_NUM:integer")->m_GlobalId, "11", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MOD_TYPES_MAX_NUM:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_STATISTICS_MENU_ENTRIES:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_STATISTICS_SKILL_ENTRIES:integer")->m_GlobalId, "6", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CHARACTER_ANIMATION_TYPES_MAX_NUM:integer")->m_GlobalId, "6", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_CLASSES_MAX_NUM:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "20", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MELEE_WEAPON_TYPES_MAX_NUM:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MOUNTED_WEAPON_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SHELL_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "8", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_AMMO_TYPES_MAX_NUM:integer")->m_GlobalId, "12", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_FLASH_TYPES_MAX_NUM:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SUB_BULLET:integer")->m_GlobalId, "0", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BRACKET_MODELS_MAX_NUM:integer")->m_GlobalId, "6", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_OF_RELOAD_SYSTEM_TYPES:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_OF_SHOOTDODGE_SYSTEM_TYPES:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_OF_HEADAIM_TYPES:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_OF_ZEN_MODE_TYPES:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NUM_OF_CONTROL_TYPES:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("GOODIE_TYPES_MAX_NUM:integer")->m_GlobalId, "24", 0);
		inst->AddStructElement(BaseType::GetTypeByName("POWER_UP_TYPES_MAX_NUM:integer")->m_GlobalId, "12", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TRACK_TYPES_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "31", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_CONFIGURAION_NODES_MAX_NUM:integer")->m_GlobalId, "34", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_ENGINE_TYPES_MAX_NUM:integer")->m_GlobalId, "7", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_POSES_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COMBO_STRINGS_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COMBO_MOVES_MAX_NUM:integer")->m_GlobalId, "24", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COMBO_ENEMY_STATE_MAX_NUM:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NormalKillColor:vector")->m_GlobalId, "1.000000 1.000000 0.690000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("ExplosionKillColor:vector")->m_GlobalId, "0.800000 0.000000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VehicleKillColor:vector")->m_GlobalId, "0.000000 1.000000 0.250000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("UniqueKillColor:vector")->m_GlobalId, "0.840000 0.620000 0.120000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RaceBonusColor:vector")->m_GlobalId, "0.800000 0.800000 0.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("OverallBonusColor:vector")->m_GlobalId, "0.600000 0.000000 0.900000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAX_SUB_MOVE_CTRLS:integer")->m_GlobalId, "7", 0);
		inst->AddStructElement(BaseType::GetTypeByName("DECALS_MAX_NUM:integer")->m_GlobalId, "34", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PARTICLE_EFFECTS_MAX_NUM:integer")->m_GlobalId, "228", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SOUND_BACKGROUNDMUSIC_MAX_NUM:integer")->m_GlobalId, "23", 0);
		inst->AddStructElement(BaseType::GetTypeByName("GENERAL_AND_PLAYER_SOUND_EFFECTS_MAX_NUM:integer")->m_GlobalId, "146", 0);
		inst->AddStructElement(BaseType::GetTypeByName("UNIQUE_COMBO_MOVE_SOUNDS_MAX_NUM:integer")->m_GlobalId, "17", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BULLET_SOUND_EFFECTS_MAX_NUM:integer")->m_GlobalId, "26", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAX_MISSION_TAUNTS:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAX_SUB_MISSION_TAUNTS:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAX_RANDOM_TAUNTS:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("COMBO_MUSIC_MAX_NUM:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_SOUNDS_MAX_NUM:integer")->m_GlobalId, "21", 0);
		inst->AddStructElement(BaseType::GetTypeByName("VEHICLE_ENGINE_SOUNDS_MAX_NUM:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("DEST_OBJECTS_SOUND_DICTS_MAX_NUM:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("DEST_OBJECT_SOUNDS_MAX_NUM:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_SOUNDS_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SHELL_SOUNDS_MAX_NUM:integer")->m_GlobalId, "3", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TARGET_ANY:integer")->m_GlobalId, "1023", 0);
		inst->AddStructElement(BaseType::GetTypeByName("FACTION_MODIFIED_INDEX:integer")->m_GlobalId, "19", 0);
		inst->AddStructElement(BaseType::GetTypeByName("FACTION_MAX:integer")->m_GlobalId, "38", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RELATION_ANY:integer")->m_GlobalId, "1023", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PHYSIC_TYPES_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("WEAPON_ANIM_TYPES_MAX_NUM:integer")->m_GlobalId, "7", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RELOAD_ANIM_TYPES_MAX_NUM:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CLOSE_COMBAT_MAX_MOVES:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("JUMP_SUB_TYPES_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TAKE_A_HIT_AIRBORNE_POSITIONS_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TAKE_A_HIT_AIRBORNE_STATES_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TAKE_A_HIT_POSITIONS_MAX_POS:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TAKE_A_HIT_TYPES_MAX_NUM:integer")->m_GlobalId, "2", 0);
		inst->AddStructElement(BaseType::GetTypeByName("JUMP_STATES_MAX_NUM:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("ANIMATION_IDLE_POSES_MAX_NUM:integer")->m_GlobalId, "24", 0);
		inst->AddStructElement(BaseType::GetTypeByName("ANIMATION_PLAYER_IDLE_POSES_MAX_NUM:integer")->m_GlobalId, "6", 0);
		inst->AddStructElement(BaseType::GetTypeByName("ANIMATION_FACIALS_MAX_NUM:integer")->m_GlobalId, "11", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RUMBLE_TYPES_MAX_NUM:integer")->m_GlobalId, "10", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CTRL_BONE_INDEX_MAX_NUM:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PROP_TYPES_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("HUD_MENU_OPTIONS_MAX_NUM:integer")->m_GlobalId, "7", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MENU_LIST_NUMBER_MAX_NUM:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("HUD_SCORE_BAR_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("BLIP_TYPES_MAX_NUM:integer")->m_GlobalId, "15", 0);
		inst->AddStructElement(BaseType::GetTypeByName("HUD_MAINMENU_GFX_TYPES_MAX_NUM:integer")->m_GlobalId, "20", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TUTORIAL_MENU_MAX_NUM:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("TUTORIAL_ENTRIES_MAX_NUM:integer")->m_GlobalId, "11", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SPECIFIC_MISSION_LAST_MAIN_MISSION:integer")->m_GlobalId, "29", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SPECIFIC_MISSION_MAX_NUM:integer")->m_GlobalId, "81", 0);
		inst->AddStructElement(BaseType::GetTypeByName("AWARD_TYPE_MAX_NUM:integer")->m_GlobalId, "62", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PLAYER_INPUT_ACTIONS_MAX_NUM:integer")->m_GlobalId, "53", 0);
		inst->AddStructElement(BaseType::GetTypeByName("KEYSTRING_INDEX_MAX_NUM:integer")->m_GlobalId, "129", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MODEL_CHARACTER_MAX_NUM:integer")->m_GlobalId, "32", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MODEL_WEAR_MAX_NUM:integer")->m_GlobalId, "27", 0);
		inst->AddStructElement(BaseType::GetTypeByName("LOADING_BLOCK_ID_MAX:integer")->m_GlobalId, "6", 0);
		inst->AddStructElement(BaseType::GetTypeByName("MAPS_MAX:integer")->m_GlobalId, "9", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SUBMAPS_MAX:integer")->m_GlobalId, "21", 0);
		inst->AddStructElement(BaseType::GetTypeByName("LOCATIONS_MAX_NUM:integer")->m_GlobalId, "14", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NEIGHBORHOODS_MAX:integer")->m_GlobalId, "22", 0);
		inst->AddStructElement(BaseType::GetTypeByName("NEIGHBORHOOD_SUPMAPS_INDEX:integer")->m_GlobalId, "8", 0);
		inst->AddStructElement(BaseType::GetTypeByName("CHARACTER_TYPES_MAX:integer")->m_GlobalId, "88", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_TYPES_MAX:integer")->m_GlobalId, "", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_WEAPON_TYPES_MAX:integer")->m_GlobalId, "22", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_WEAR_TYPES_MAX:integer")->m_GlobalId, "16", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_DISCUSSION_TYPES_MAX:integer")->m_GlobalId, "7", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_CHILL_WALL_TYPES_MAX:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_PANIC_TYPES_MAX:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("PEDESTRIAN_INTEREST_POINT_TYPES_MAX:integer")->m_GlobalId, "5", 0);
		inst->AddStructElement(BaseType::GetTypeByName("RELEASE_CHEATS_MAX_NUM:integer")->m_GlobalId, "4", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SIZE_STANDARD_ODPS2_FONT:vector")->m_GlobalId, "0.700000 0.750000 1.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SIZE_LARGE_ODPS2_FONT:vector")->m_GlobalId, "1.000000 1.000000 1.000000", 0);
		inst->AddStructElement(BaseType::GetTypeByName("SPACING_STANDARD_ODPS2_FONT:number")->m_GlobalId, "2.000000", 0);

		inst->CalculateSize();

		return inst;
	}
};

common::Create();