class common : public Scriptbaked
{
public:
	static Scriptbaked* Create()
	{
		static Scriptbaked* inst = new Scriptbaked("common", "Node", true, false);

		inst->AddMember(GetScriptIdByFullName("identity_quaternion:quaternion"), "1.000000 0.000000 0.000000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("default_Gravity:vector"), "0.000000 -10.000000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("default_timestep:number"), "0.040000", 0);
		inst->AddMember(GetScriptIdByFullName("radian_to_degrees:number"), "57.295780", 0);
		inst->AddMember(GetScriptIdByFullName("null_string:string"), 0, 0);
		inst->AddMember(GetScriptIdByFullName("dont_fix_orient:truth"), "false", 0);
		inst->AddMember(GetScriptIdByFullName("torso_vertical_orient:quaternion"), "0.707107 0.707107 0.000000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("legs_vertical_orient:quaternion"), "0.707107 -0.707107 0.000000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("subdir:Entity"), "", 0);
		inst->AddMember(GetScriptIdByFullName("foundancester:truth"), "", 0);
		inst->AddMember(GetScriptIdByFullName("gamename:string"), "", 0);
		inst->AddMember(GetScriptIdByFullName("PLAYER_NODE:Entity"), "", 0);
		inst->AddMember(GetScriptIdByFullName("GENERAL_CUTSCENEPLAYING:truth"), "", 0);
		inst->AddMember(GetScriptIdByFullName("LAST_DYNAMIC_SOUNDENTITY:Entity"), "", 0);
		inst->AddMember(GetScriptIdByFullName("GENERAL_NONSHOOTING_ENEMY:truth"), "", 0);
		inst->AddMember(GetScriptIdByFullName("DEFAULT_VEHICLE_OFFSET:number"), "-1.388272", 0);
		inst->AddMember(GetScriptIdByFullName("EMPTY_STRING:string"), "", 0);
		inst->AddMember(GetScriptIdByFullName("DB_ANIMDICT:Entity"), "", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_DISABLE:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_DYNAMIC:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_INVISIBLE:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_COLL_DISABLE:integer"), "64", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_FRAGMENT_UNLOADED:integer"), "256", 0);
		inst->AddMember(GetScriptIdByFullName("NODE_PURGENAMES:integer"), "512", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_NONE:integer"), "0", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_SOLID:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_BULLETPROOF:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_OPAQUE:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_CAMERABLOCK:integer"), "8", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_TRIGGER:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_NAVIGATIONBLOCK:integer"), "32", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_PHYSICSONLY:integer"), "64", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_ACTIVATE_TRIGGER:integer"), "128", 0);
		inst->AddMember(GetScriptIdByFullName("COLL_ALL:integer"), "1024", 0);
		inst->AddMember(GetScriptIdByFullName("BIT1:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("BIT2:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("BIT3:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("BIT4:integer"), "8", 0);
		inst->AddMember(GetScriptIdByFullName("BIT5:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("BIT6:integer"), "32", 0);
		inst->AddMember(GetScriptIdByFullName("BIT7:integer"), "64", 0);
		inst->AddMember(GetScriptIdByFullName("BIT8:integer"), "128", 0);
		inst->AddMember(GetScriptIdByFullName("BIT9:integer"), "256", 0);
		inst->AddMember(GetScriptIdByFullName("BIT10:integer"), "512", 0);
		inst->AddMember(GetScriptIdByFullName("BIT11:integer"), "1024", 0);
		inst->AddMember(GetScriptIdByFullName("BIT12:integer"), "2048", 0);
		inst->AddMember(GetScriptIdByFullName("BIT13:integer"), "4096", 0);
		inst->AddMember(GetScriptIdByFullName("GOD_MODE_LIMIT:number"), "2000.000000", 0);
		inst->AddMember(GetScriptIdByFullName("MAX_TIME_ZONES:integer"), "29", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_NORMAL:integer"), "0", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_FREEFALL:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_ABSOLUTE:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_SLIDE:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_TAKEOFF:integer"), "8", 0);
		inst->AddMember(GetScriptIdByFullName("PIVOT_DEFAULT:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("BASE_TYPES_MAX_NUM:integer"), "24", 0);
		inst->AddMember(GetScriptIdByFullName("CHARACTER_TYPES_MAX_NUM:integer"), "23", 0);
		inst->AddMember(GetScriptIdByFullName("ANIMAL_SUB_TYPES_MAX_NUM:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("TARGET_DUMMY_SUB_TYPES_MAX_NUM:integer"), "1", 0);
		inst->AddMember(GetScriptIdByFullName("CAMERA_SUB_TYPES_MAX_NUM:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("OBJECT_SUB_TYPES_MAX_NUM:integer"), "100", 0);
		inst->AddMember(GetScriptIdByFullName("PLACEHOLDER_SUB_TYPES_MAX_NUM:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("PLACEHOLDER_PRIORITIES_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("RESOURCE_TYPES_MAX_NUM:integer"), "11", 0);
		inst->AddMember(GetScriptIdByFullName("MOD_TYPES_MAX_NUM:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_STATISTICS_MENU_ENTRIES:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_STATISTICS_SKILL_ENTRIES:integer"), "6", 0);
		inst->AddMember(GetScriptIdByFullName("CHARACTER_ANIMATION_TYPES_MAX_NUM:integer"), "6", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_CLASSES_MAX_NUM:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_SUB_TYPES_MAX_NUM:integer"), "20", 0);
		inst->AddMember(GetScriptIdByFullName("MELEE_WEAPON_TYPES_MAX_NUM:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("MOUNTED_WEAPON_SUB_TYPES_MAX_NUM:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("SHELL_SUB_TYPES_MAX_NUM:integer"), "8", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_AMMO_TYPES_MAX_NUM:integer"), "12", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_FLASH_TYPES_MAX_NUM:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("SUB_BULLET:integer"), "0", 0);
		inst->AddMember(GetScriptIdByFullName("BRACKET_MODELS_MAX_NUM:integer"), "6", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_OF_RELOAD_SYSTEM_TYPES:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_OF_SHOOTDODGE_SYSTEM_TYPES:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_OF_HEADAIM_TYPES:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_OF_ZEN_MODE_TYPES:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("NUM_OF_CONTROL_TYPES:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("GOODIE_TYPES_MAX_NUM:integer"), "24", 0);
		inst->AddMember(GetScriptIdByFullName("POWER_UP_TYPES_MAX_NUM:integer"), "12", 0);
		inst->AddMember(GetScriptIdByFullName("TRACK_TYPES_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_SUB_TYPES_MAX_NUM:integer"), "31", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_CONFIGURAION_NODES_MAX_NUM:integer"), "34", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_ENGINE_TYPES_MAX_NUM:integer"), "7", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_POSES_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("COMBO_STRINGS_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("COMBO_MOVES_MAX_NUM:integer"), "24", 0);
		inst->AddMember(GetScriptIdByFullName("COMBO_ENEMY_STATE_MAX_NUM:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("NormalKillColor:vector"), "1.000000 1.000000 0.690000", 0);
		inst->AddMember(GetScriptIdByFullName("ExplosionKillColor:vector"), "0.800000 0.000000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("VehicleKillColor:vector"), "0.000000 1.000000 0.250000", 0);
		inst->AddMember(GetScriptIdByFullName("UniqueKillColor:vector"), "0.840000 0.620000 0.120000", 0);
		inst->AddMember(GetScriptIdByFullName("RaceBonusColor:vector"), "0.800000 0.800000 0.000000", 0);
		inst->AddMember(GetScriptIdByFullName("OverallBonusColor:vector"), "0.600000 0.000000 0.900000", 0);
		inst->AddMember(GetScriptIdByFullName("MAX_SUB_MOVE_CTRLS:integer"), "7", 0);
		inst->AddMember(GetScriptIdByFullName("DECALS_MAX_NUM:integer"), "34", 0);
		inst->AddMember(GetScriptIdByFullName("PARTICLE_EFFECTS_MAX_NUM:integer"), "228", 0);
		inst->AddMember(GetScriptIdByFullName("SOUND_BACKGROUNDMUSIC_MAX_NUM:integer"), "23", 0);
		inst->AddMember(GetScriptIdByFullName("GENERAL_AND_PLAYER_SOUND_EFFECTS_MAX_NUM:integer"), "146", 0);
		inst->AddMember(GetScriptIdByFullName("UNIQUE_COMBO_MOVE_SOUNDS_MAX_NUM:integer"), "17", 0);
		inst->AddMember(GetScriptIdByFullName("BULLET_SOUND_EFFECTS_MAX_NUM:integer"), "26", 0);
		inst->AddMember(GetScriptIdByFullName("MAX_MISSION_TAUNTS:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("MAX_SUB_MISSION_TAUNTS:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("MAX_RANDOM_TAUNTS:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("COMBO_MUSIC_MAX_NUM:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_SOUNDS_MAX_NUM:integer"), "21", 0);
		inst->AddMember(GetScriptIdByFullName("VEHICLE_ENGINE_SOUNDS_MAX_NUM:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("DEST_OBJECTS_SOUND_DICTS_MAX_NUM:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("DEST_OBJECT_SOUNDS_MAX_NUM:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_SOUNDS_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("SHELL_SOUNDS_MAX_NUM:integer"), "3", 0);
		inst->AddMember(GetScriptIdByFullName("TARGET_ANY:integer"), "1023", 0);
		inst->AddMember(GetScriptIdByFullName("FACTION_MODIFIED_INDEX:integer"), "19", 0);
		inst->AddMember(GetScriptIdByFullName("FACTION_MAX:integer"), "38", 0);
		inst->AddMember(GetScriptIdByFullName("RELATION_ANY:integer"), "1023", 0);
		inst->AddMember(GetScriptIdByFullName("PHYSIC_TYPES_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("WEAPON_ANIM_TYPES_MAX_NUM:integer"), "7", 0);
		inst->AddMember(GetScriptIdByFullName("RELOAD_ANIM_TYPES_MAX_NUM:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("CLOSE_COMBAT_MAX_MOVES:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("JUMP_SUB_TYPES_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("TAKE_A_HIT_AIRBORNE_POSITIONS_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("TAKE_A_HIT_AIRBORNE_STATES_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("TAKE_A_HIT_POSITIONS_MAX_POS:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("TAKE_A_HIT_TYPES_MAX_NUM:integer"), "2", 0);
		inst->AddMember(GetScriptIdByFullName("JUMP_STATES_MAX_NUM:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("ANIMATION_IDLE_POSES_MAX_NUM:integer"), "24", 0);
		inst->AddMember(GetScriptIdByFullName("ANIMATION_PLAYER_IDLE_POSES_MAX_NUM:integer"), "6", 0);
		inst->AddMember(GetScriptIdByFullName("ANIMATION_FACIALS_MAX_NUM:integer"), "11", 0);
		inst->AddMember(GetScriptIdByFullName("RUMBLE_TYPES_MAX_NUM:integer"), "10", 0);
		inst->AddMember(GetScriptIdByFullName("CTRL_BONE_INDEX_MAX_NUM:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("PROP_TYPES_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("HUD_MENU_OPTIONS_MAX_NUM:integer"), "7", 0);
		inst->AddMember(GetScriptIdByFullName("MENU_LIST_NUMBER_MAX_NUM:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("HUD_SCORE_BAR_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("BLIP_TYPES_MAX_NUM:integer"), "15", 0);
		inst->AddMember(GetScriptIdByFullName("HUD_MAINMENU_GFX_TYPES_MAX_NUM:integer"), "20", 0);
		inst->AddMember(GetScriptIdByFullName("TUTORIAL_MENU_MAX_NUM:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("TUTORIAL_ENTRIES_MAX_NUM:integer"), "11", 0);
		inst->AddMember(GetScriptIdByFullName("SPECIFIC_MISSION_LAST_MAIN_MISSION:integer"), "29", 0);
		inst->AddMember(GetScriptIdByFullName("SPECIFIC_MISSION_MAX_NUM:integer"), "81", 0);
		inst->AddMember(GetScriptIdByFullName("AWARD_TYPE_MAX_NUM:integer"), "62", 0);
		inst->AddMember(GetScriptIdByFullName("PLAYER_INPUT_ACTIONS_MAX_NUM:integer"), "53", 0);
		inst->AddMember(GetScriptIdByFullName("KEYSTRING_INDEX_MAX_NUM:integer"), "129", 0);
		inst->AddMember(GetScriptIdByFullName("MODEL_CHARACTER_MAX_NUM:integer"), "32", 0);
		inst->AddMember(GetScriptIdByFullName("MODEL_WEAR_MAX_NUM:integer"), "27", 0);
		inst->AddMember(GetScriptIdByFullName("LOADING_BLOCK_ID_MAX:integer"), "6", 0);
		inst->AddMember(GetScriptIdByFullName("MAPS_MAX:integer"), "9", 0);
		inst->AddMember(GetScriptIdByFullName("SUBMAPS_MAX:integer"), "21", 0);
		inst->AddMember(GetScriptIdByFullName("LOCATIONS_MAX_NUM:integer"), "14", 0);
		inst->AddMember(GetScriptIdByFullName("NEIGHBORHOODS_MAX:integer"), "22", 0);
		inst->AddMember(GetScriptIdByFullName("NEIGHBORHOOD_SUPMAPS_INDEX:integer"), "8", 0);
		inst->AddMember(GetScriptIdByFullName("CHARACTER_TYPES_MAX:integer"), "88", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_TYPES_MAX:integer"), "", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_WEAPON_TYPES_MAX:integer"), "22", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_WEAR_TYPES_MAX:integer"), "16", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_DISCUSSION_TYPES_MAX:integer"), "7", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_CHILL_WALL_TYPES_MAX:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_PANIC_TYPES_MAX:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("PEDESTRIAN_INTEREST_POINT_TYPES_MAX:integer"), "5", 0);
		inst->AddMember(GetScriptIdByFullName("RELEASE_CHEATS_MAX_NUM:integer"), "4", 0);
		inst->AddMember(GetScriptIdByFullName("SIZE_STANDARD_ODPS2_FONT:vector"), "0.700000 0.750000 1.000000", 0);
		inst->AddMember(GetScriptIdByFullName("SIZE_LARGE_ODPS2_FONT:vector"), "1.000000 1.000000 1.000000", 0);
		inst->AddMember(GetScriptIdByFullName("SPACING_STANDARD_ODPS2_FONT:number"), "2.000000", 0);

		inst->CalculateSize();

		return inst;
	}
};

common::Create();