#pragma once

#include "stdafx.h"

#include "StringsPool.h"
#include "Entity.h"
#include "RewindBuffer.h"
#include "EditorCamera.h"

class CollisionProbe;

struct Scene_Buffer24
{
	int field_0;
	int field_4;
	int field_8;
	int field_C;
	int field_10;
	int field_14;
};

struct Scene_Buffer80
{
	int field_0;
	int field_4;
	int field_8;
	int field_C;
	int field_10;
	int field_14;
	int field_18;
	int field_1C;
	int field_20;
	int field_24;
	int field_28;
	int field_2C;
	int field_30;
	int field_34;
	int field_38;
	int field_3C;
	int field_40;
	int field_44;
	int field_48;
	int field_4C;
};


class SceneGame
{
private:
		void* lpVtbl;
		int field_4;
		int field_8;
		int field_C;
		int field_10;
		int field_14;
		int field_18;
		int field_1C;
		int field_20;
		int field_24;
		int field_28;
		int field_2C;
		AuxQuadTree* m_pQuadTree;
		int field_34;
		int field_38;
		int field_3C;
		int field_40;
		EditorCamera* m_pEditorCamera;
		Fragment* m_pUnkFragment;
		int field_4C;
		int field_50;
		Scene_Buffer24* m_pBuffer24;
		int field_58;
		int field_5C;
		Entity* m_pCamera;
		Entity* m_pUnkEntityPtr;
		int field_68;
		Entity* m_pEntity;
		int field_70;
		int field_74;
		int field_78;
		int field_7C;
		int field_80;
		int field_84;
		int field_88;
		int field_8C;
		int field_90;
		int field_94;
		int field_98;
		int field_9C;
		int field_A0;
		int field_A4;
		CollisionProbe* m_pSharedProbe;
		RewindBuffer* m_pRewindBuffer1;
		RewindBuffer* m_pRewindBuffer2;
		int field_B4;
		int field_B8;
		int field_BC;
		int field_C0;
		int field_C4;
		int field_C8;
		int field_CC;
		int field_D0;
		int field_D4;
		int field_D8;
		int field_DC;
		int field_E0;
		int field_E4;
		int field_E8;
		int field_EC;
		int field_F0;
		int field_F4;
		int field_F8;
		int field_FC;
		int field_100;
		int field_104;
		int field_108;
		int m_nUnkNodesCount;
		int field_110;
		float field_114;
		float field_118;
		float field_11C;
		byte m_bFixedFramerate[4];
		float m_fFixedFramerateVal;
		int field_128;
		int field_12C;
		int field_130;
		int field_134;
		int field_138;
		int field_13C;
		int field_140;
		int field_144;
		int field_148;
		int field_14C;
		int field_150;
		int field_154;
		int field_158;
		int field_15C;
		int field_160;
		int field_164;
		int field_168;
		int field_16C;
		int m_nSavePointOperationError;
		String m_sSaveDir;
		int m_nMemoryCardIndex;
		int m_nSaveSlotIndex;
		int* field_188;
		int m_nSaveGameSize;
		int field_190;
		Vector4<float> m_vUnkBounds;
		byte field_1A4;
		byte field_1A5;
		byte field_1A6;
		byte field_1A7;
		int field_1A8;
		int field_1AC[1];
		int field_1B0;
		int field_1B4;
		int field_1B8;
		int field_1BC;
		int field_1C0;
		int field_1C4;
		int field_1C8;
		int field_1CC;
		int field_1D0;
		int field_1D4;
		int field_1D8;
		int field_1DC;
		int field_1E0;
		int field_1E4;
		int field_1E8;
		int field_1EC;
		int field_1F0;
		int field_1F4;
		int field_1F8;
		int field_1FC;
		int field_200;
		int field_204;
		int field_208;
		int field_20C;
		int field_210;
		int field_214;
		int field_218;
		int field_21C;
		int field_220;
		int field_224;
		int field_228;
		int field_22C;
		int field_230;
		int field_234;
		int field_238;
		int field_23C;
		int field_240;
		int field_244;
		int field_248;
		int field_24C;
		Scene_Buffer80* field_250;
		Scene_Buffer80* field_254;
		int m_nLoadTime;
		int m_nTimeMilliseconds_1;
		int m_nTimeMilliseconds;
		int field_264;

};

