#include "MeshBuffer_Dx9.h"
#include "GfxInternal_Dx9.h"

LPDIRECT3DVERTEXDECLARATION9 MeshBuffer_Dx9::StaticVertexDeclaration[4];
bool MeshBuffer_Dx9::StaticVertexDeclarationCreated;

MeshBuffer_Dx9::~MeshBuffer_Dx9()
{
	MESSAGE_CLASS_DESTROYED(MeshBuffer_Dx9);
}

void MeshBuffer_Dx9::SetMeshDataAsCurrent() const
{
	g_GfxInternal_Dx9->m_Direct3DDevice->SetStreamSource(0, m_VertexBuffer->m_Direct3DVertexBuffer, 0, m_VertexBuffer->m_Stride);
	g_GfxInternal_Dx9->SetVertexBuffer(m_VertexBuffer);

	g_GfxInternal_Dx9->m_Direct3DDevice->SetIndices(m_IndexBuffer->m_Direct3DIndexBuffer);
	g_GfxInternal_Dx9->SetIndexBuffer(m_IndexBuffer);
}

#pragma message(TODO_IMPLEMENTATION)
void MeshBuffer_Dx9::SWSkin()
{
}

char* MeshBuffer_Dx9::LockAndGetVertexBufferPtr(const int mode)
{
	return m_VertexBuffer->LockAndGetBufferPtr(mode);
}

void MeshBuffer_Dx9::CreateStaticVertexDeclaration()
{
	D3DVERTEXELEMENT9 Vert1[] =
	{
		{ NULL, NULL, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, NULL },
		{ NULL, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, NULL },
		{ NULL, 24, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, NULL },
		{ 1, NULL, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, NULL },
		D3DDECL_END()
	};

	g_GfxInternal_Dx9->m_Direct3DDevice->CreateVertexDeclaration(Vert1, &StaticVertexDeclaration[0]);

	D3DVERTEXELEMENT9 Vert2[] =
	{
		{ NULL, NULL, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, NULL },
		{ NULL, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, NULL },
		{ NULL, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 1 },
		{ NULL, 28, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, NULL },
		{ 1, NULL, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, NULL },
		D3DDECL_END()
	};

	g_GfxInternal_Dx9->m_Direct3DDevice->CreateVertexDeclaration(Vert2, &StaticVertexDeclaration[1]);

	D3DVERTEXELEMENT9 Vert3[] =
	{
		{ NULL, NULL, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, NULL },
		{ NULL, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, NULL },
		{ NULL, 24, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, NULL },
		{ NULL, 32, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1 },
		{ 1, NULL, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, NULL },
		D3DDECL_END()
	};

	g_GfxInternal_Dx9->m_Direct3DDevice->CreateVertexDeclaration(Vert3, &StaticVertexDeclaration[2]);

	D3DVERTEXELEMENT9 Vert4[] =
	{
		{ NULL, NULL, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, NULL },
		{ NULL, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, NULL },
		{ NULL, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 1 },
		{ NULL, 28, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, NULL },
		{ NULL, 36, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 1 },
		{ 1, NULL, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, NULL },
		D3DDECL_END()
	};

	g_GfxInternal_Dx9->m_Direct3DDevice->CreateVertexDeclaration(Vert4, &StaticVertexDeclaration[3]);
}